[project]
name = "realsense-colmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Graham Clifford", email = "gjcliff@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "open3d>=0.20.0",
    "opencv-python>=5.0.0.93",
    "pycolmap>=4.2.0",
    "pyrealsense2>=2.58.4.10922",
    "rerun-sdk>=0.38.1",
    "tqdm>=4.70.1",
]

[project.scripts]
realsense-colmap = "realsense_colmap:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
